name       : qt6-serialbus
version    : 6.3.0
release    : 2
source     :
    - https://download.qt.io/official_releases/qt/6.3/6.3.0/submodules/qtserialbus-everywhere-src-6.3.0.tar.xz : d2f6c988cb36e76956b8828cdc17513c0677b5523f635fc30a920701bb3627d6
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt module for general purpose serial bus access
description: |
    Qt module for general purpose serial bus access
builddeps  :
    - pkgconfig(Qt6SerialPort)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
