name       : qt6-serialbus
version    : 6.2.2
release    : 1
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.2/submodules/qtserialbus-everywhere-src-6.2.2.tar.xz : fa15d29a5c213b32e7298b2459fc5790c9eee376ab06aeb47a9e15a59b6e8473
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt module for general purpose serial bus access
description: |
    Qt module for general purpose serial bus access
builddeps  :
    - pkgconfig(Qt6SerialPort)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
